image:
  repository: harbor.apps.dso.numerique-interieur.com/form-formation11/java-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "tuto"

ingress:
  host: test.formation-app.cpin.numerique-interieur.com

# Contrainte de sécurité Openshift
postgres:
  auth:
    existingSecret: pg-secret
    secretKeys:
      passwordKey: "PG_PASSWORD"
      userPasswordKey: "PG_PASSWORD"
      adminPasswordKey: "PG_ROOT_PASSWORD"
    username: "userdemo"
    database: "userdemo"

