# Default values for demo-java-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.apps.dso.numerique-interieur.com/mi-demosign/app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "demo-sign"

imagePullSecrets: 
  - name: "registry-pull-secret"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  secret:
    enabled: true
  host: demosign.apps.app1.numerique-interieur.com

resources: 
  limits:
    memory: "512Mi"
    cpu: "500m"  
  requests:
    memory: "512Mi"
    cpu: "100m"  

global: 
  postgresql:
    auth:
      postgresPassword: "MySupErPaSSwOrd"
      username: "userdemo"
      password: "passworddemo"
      database: "demodb"

# Contrainte de sécurité Openshift
postgresql:
  fullnameOverride: postgres-demo
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"
  securityContext:
    enabled: false
  shmVolume:
    chmod:
      enabled: false
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  primary:
    resources: 
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
    securityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
